# Generated by Django 3.0.5 on 2020-07-14 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=100)),
                ('Price', models.IntegerField()),
                ('img', models.ImageField(upload_to='Home/images')),
            ],
        ),
    ]
