# Generated by Django 3.0.5 on 2020-07-14 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='img',
            field=models.ImageField(upload_to='images'),
        ),
    ]
