# Generated by Django 3.0.5 on 2020-07-15 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0004_auto_20200715_1106'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appetizer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=100)),
                ('Price', models.IntegerField()),
                ('img', models.ImageField(upload_to='Appetizer')),
            ],
        ),
        migrations.CreateModel(
            name='Burger',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=100)),
                ('Price', models.IntegerField()),
                ('img', models.ImageField(upload_to='Burger')),
            ],
        ),
        migrations.CreateModel(
            name='Pasta_Roll',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=100)),
                ('Price', models.IntegerField()),
                ('img', models.ImageField(upload_to='Pasta-Rol')),
            ],
        ),
        migrations.CreateModel(
            name='Sandwiche',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=100)),
                ('Price', models.IntegerField()),
                ('img', models.ImageField(upload_to='Sandwiche')),
            ],
        ),
        migrations.CreateModel(
            name='Shawarma_pltr',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=100)),
                ('Price', models.IntegerField()),
                ('img', models.ImageField(upload_to='Shwarma-pltr')),
            ],
        ),
        migrations.AlterField(
            model_name='pizza',
            name='img',
            field=models.ImageField(upload_to='pizza'),
        ),
    ]
