# Generated by Django 3.0.5 on 2020-07-21 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0006_auto_20200721_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='burger',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='shawarma_pltr',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
