# Generated by Django 3.0.5 on 2020-08-01 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0007_auto_20200721_1433'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('City_name', models.CharField(max_length=100)),
                ('street_No', models.EmailField(max_length=100)),
                ('Phone_NO', models.IntegerField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('Address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.Address')),
            ],
        ),
    ]
