# Generated by Django 3.0.5 on 2020-08-02 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0009_auto_20200802_2256'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='id',
            new_name='ID',
        ),
    ]
