# Generated by Django 3.0.5 on 2020-08-03 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0014_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='Delievery_Mode',
        ),
    ]
