# Generated by Django 3.1.4 on 2020-12-19 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0017_auto_20200803_2351'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='Password',
            field=models.CharField(default='', max_length=100),
        ),
    ]
